# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f335ff1fd43a348dbd3ab7cb78c220211fbc92fffacf5c8961d178df130e9f720ba145e5eb7b6c4f3f1a4e7f731ab91651b7d76fc5dec0ebbcb9d460ee8c32dd

test:
  secret_key_base: f1e82ff5ed94245270b370fbf8928a3b289d96ce94d3941da033f143d5723ef353e987ff373b1fca75b07d1c786f6518e208f9cedc3cd62d4c888b96dbe73ae7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
